--select sum(VALOR_CREDT) from (
	SELECT 	
		TIPO_DOCUMENTO
		,CODIGO_CUENTA_CONTABLE AS CUENTA
		,(CASE WHEN (VALOR_ITEM>0) THEN
		VALOR_ITEM ELSE 0 END) AS VALOR_CREDT
		,(CASE WHEN (VALOR_ITEM<0) THEN
		VALOR_ITEM*(-1) ELSE 0 END) AS VALOR_DEB,
		DESCRIPCION					 
	FROM 	CON.FACTURA_DETALLE AS A
	WHERE  	A.DOCUMENTO 	= 	'NM12756_1'
		AND A.REG_STATUS = 	''
	AND A.CODIGO_CUENTA_CONTABLE !='13050702'
) as a

UNION ALL(
		SELECT 	FAC.TIPO_DOCUMENTO ,
			CMC.CUENTA , 
			0 AS VALOR_CREDT, 
			sum(FACD.VALOR_ITEM) AS VALOR_DEB,
			FAC.DESCRIPCION
		FROM CON.FACTURA AS FAC
		INNER JOIN CON.FACTURA_DETALLE 	AS FACD ON ( FACD.DSTRCT = FAC.DSTRCT AND FACD.TIPO_DOCUMENTO = FAC.TIPO_DOCUMENTO AND FACD.DOCUMENTO = FAC.DOCUMENTO )
		INNER JOIN CON.CMC_DOC AS CMC	ON (FAC.TIPO_DOCUMENTO = CMC.TIPODOC AND FAC.CMC = CMC.CMC )	
		WHERE FAC.DOCUMENTO	= 	'NM12756_1'
		  AND FAC.REG_STATUS  = 	''
		  AND FACD.CODIGO_CUENTA_CONTABLE !='13050702' --tener en cuenta
		GROUP BY 
			FAC.TIPO_DOCUMENTO , 
			CMC.CUENTA ,  
			FAC.DESCRIPCION
	)
