SELECT 
	FAC.DOCUMENTO ,
	FAC.FECHA_FACTURA , 
	FAC.FECHA_VENCIMIENTO ,
	FAC.PERIODO,
	FAC.NIT,
	FAC.REFERENCIA_1 AS ID_SOLICITUD,
	CENTRO_COSTOS_INGRESO,
	CENTRO_COSTOS_GASTOS,
	FAC.DESCRIPCION,
	OFE.NUM_OS,
	FAC.PERIODO,
	fac.*
FROM CON.FACTURA as fac
LEFT JOIN OPAV.OFERTAS  AS OFE 	ON(FAC.REFERENCIA_1 = OFE.ID_SOLICITUD)
WHERE 
SUBSTRING(DOCUMENTO,1,2) = 'NM' 
AND FAC.PERIODO ='201701' 
AND FAC.REG_STATUS = '' 
AND CENTRO_COSTOS_INGRESO != ''
and fac.documento = 'NM12756_1'
ORDER BY 1	
