-----------------QUERY DETALLE-----------------
SELECT TIPO_DOCUMENTO,
	CMC.CUENTA AS CUENTA,
	CASE WHEN VALOR_FACTURA>0 THEN VALOR_FACTURA ELSE 0 END AS VALOR_DEB ,	
        CASE WHEN VALOR_FACTURA<0 THEN VALOR_FACTURA*-1 ELSE 0 END AS VALOR_CREDT,	
	DESCRIPCION AS DESCRIPCION,
	DOCUMENTO AS DOCUMENTO 
FROM CON.FACTURA FAC
INNER JOIN CON.CMC_DOC AS CMC  ON (CMC.CMC = FAC.CMC AND CMC.TIPODOC = FAC.TIPO_DOCUMENTO) 
WHERE DOCUMENTO = 'R0032227'
 AND TIPO_DOCUMENTO = 'FAC'
 AND FAC.REG_STATUS = ''
 AND NIT = '9000742958'

UNION ALL

SELECT TIPO_DOCUMENTO,
	CODIGO_CUENTA_CONTABLE AS CUENTA,
        CASE WHEN VALOR_UNITARIO<0 THEN VALOR_UNITARIO*-1 ELSE 0 END AS VALOR_DEB,
	CASE WHEN VALOR_UNITARIO>0 THEN VALOR_UNITARIO ELSE 0 END AS  VALOR_CREDT,	
	DESCRIPCION AS DESCRIPCION,
	DOCUMENTO AS DOCUMENTO 
FROM CON.FACTURA_DETALLE FAC
WHERE DOCUMENTO = 'R0032227' 
  AND TIPO_DOCUMENTO = 'FAC'
  AND REG_STATUS = ''
  AND NIT = '9000742958'

-------QUERY PRINCIPAL------
SELECT					
	F.TIPO_DOCUMENTO,					
	F.NIT,					
	F.DOCUMENTO,
	F.VALOR_FACTURAME AS VALOR_FACTURA,					
	F.FECHA_FACTURA,
	F.FECHA_VENCIMIENTO,					
	F.DESCRIPCION,
	F.PERIODO                           
FROM CON.FACTURA F 
LEFT JOIN CON.FACTURA_DETALLE DET ON ( DET.DSTRCT = F.DSTRCT AND DET.TIPO_DOCUMENTO = F.TIPO_DOCUMENTO AND DET.DOCUMENTO = F.DOCUMENTO  )
WHERE F.NIT='9000742958' 
	AND REPLACE(SUBSTRING(F.CREATION_DATE,1,7),'-','') ='201701'
	AND F.REG_STATUS = ''
	AND F.DOCUMENTO LIKE 'R%'
	AND COALESCE(F.PROCESADO,'N')='N'	
GROUP BY 1,2,3,4,5,6,7,8
ORDER BY F.FECHA_FACTURA ASC

