-- Function: con.interfaz_sl_egreso_pago_prov_provint_apoteosys()

-- DROP FUNCTION con.interfaz_sl_egreso_pago_prov_provint_apoteosys();

CREATE OR REPLACE FUNCTION con.interfaz_sl_egreso_pago_prov_provint_apoteosys()
  RETURNS text AS
$BODY$

DECLARE
 /************************************************
  *DESCRIPCION: 
  *AUTOR		:=		@BTERRAZA
  *FECHA CREACION	:=		2018-01-10
  *LAST_UPDATE		:=	 	2018-01-10
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/


EGRESO_RECORD RECORD;
INFOITEMS_ RECORD;
INFOCLIENTE RECORD;
LONGITUD NUMERIC;
SECUENCIA_GEN INTEGER;
SECUENCIA_INT INTEGER:= 1;
CUENTAS_IVA VARCHAR[] := '{}';
FECHADOC_ VARCHAR:= '';
MCTYPE CON.TYPE_INSERT_MC;
SW TEXT:='N';
VALIDACIONES TEXT;
_EXISTE CHARACTER VARYING :='';


BEGIN
		
	--Paso 2 Dinamica egreso pago a Proveedores por cuenta de Provintegral
	FOR EGRESO_RECORD IN 

			--query principal
				SELECT					
					F.TIPO_DOCUMENTO,					
					F.NIT,					
					F.DOCUMENTO,
					F.VALOR_FACTURAME AS VALOR_FACTURA,					
					F.FECHA_FACTURA,
					F.FECHA_VENCIMIENTO,					
					F.DESCRIPCION,
					F.PERIODO                           
				FROM CON.FACTURA F 
				LEFT JOIN CON.FACTURA_DETALLE DET ON ( DET.DSTRCT = F.DSTRCT AND DET.TIPO_DOCUMENTO = F.TIPO_DOCUMENTO AND DET.DOCUMENTO = F.DOCUMENTO  )
				WHERE F.NIT='9000742958' 
				  AND REPLACE(SUBSTRING(F.CREATION_DATE,1,7),'-','') ='201701'
				  AND F.REG_STATUS = ''
				  AND F.DOCUMENTO LIKE 'R%'
				  AND COALESCE(F.PROCESADO,'N')='N'	
				GROUP BY 1,2,3,4,5,6,7,8
				ORDER BY F.FECHA_FACTURA ASC

			
			--SELECT CON.interfaz_sl_egreso_pago_prov_provint_apoteosys();
			--SELECT * FROM CON.MC_EGRE_PROV_PROVINT WHERE MC_____CODIGO____CD_____B='IN' AND MC_____NUMERO____PERIOD_B=1;
			--UPDATE EGRESODET SET PROCESADO = 'N' WHERE PROCESADO = 'S' AND DOCUMENT_NO = 'BC3210' AND TIPO_DOCUMENTO = 'FAP';
			--SELECT * FROM CON.FACTURA LIMIT 10
			
						    
	LOOP					
		
		SELECT INTO INFOCLIENTE
			'NIT' AS TIPO_DOC,
			(CASE 
			WHEN GRAN_CONTRIBUYENTE ='N' AND AGENTE_RETENEDOR ='N' THEN 'RCOM' 
			WHEN GRAN_CONTRIBUYENTE ='N' AND AGENTE_RETENEDOR ='S' THEN 'RCAU' 
			WHEN GRAN_CONTRIBUYENTE ='S' AND AGENTE_RETENEDOR ='N' THEN 'GCON' 
			WHEN GRAN_CONTRIBUYENTE ='S' AND AGENTE_RETENEDOR ='S' THEN 'GCAU'
			ELSE 'PNAL' END) AS CODIGO,
			'08001'AS CODIGOCIU,
			(D.NOMBRE1||' '||D.NOMBRE2) AS NOMBRE_CORTO, 
			PAYMENT_NAME AS  NOMBRE,
			(D.APELLIDO1||' '||D.APELLIDO2) AS APELLIDOS,
			DIRECCION,
			TELEFONO			
		FROM PROVEEDOR PROV
		LEFT JOIN NIT D ON(D.CEDULA=PROV.NIT)
		LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
		WHERE NIT =  EGRESO_RECORD.NIT;	

		----SECUENCIA GENERAL
		SELECT INTO SECUENCIA_GEN  NEXTVAL('CON.INTERFAZ_SECUENCIA_EGRESO_APOTEOSYS');		

		MCTYPE.MC_____CODIGO____CONTAB_B := 'FINT'; 
		MCTYPE.MC_____CODIGO____TD_____B := 'EGRN'; 
		MCTYPE.MC_____CODIGO____CD_____B := 'EGPP'; 
		MCTYPE.MC_____NUMERO____B := SECUENCIA_GEN; --SECUENCIA GENERAL
		SECUENCIA_INT:=1;	

		/**BUSCAMOS LA INFORMACION COMPLETA QUE CONFORMARA EL ASIENTO CONTABLE PARA MANDARLO A APOTEOSYS*/

		FOR INFOITEMS_ IN			
				
					SELECT TIPO_DOCUMENTO,
						CMC.CUENTA AS CUENTA,
						CASE WHEN VALOR_FACTURA>0 THEN VALOR_FACTURA ELSE 0 END AS VALOR_DEB ,	
						CASE WHEN VALOR_FACTURA<0 THEN VALOR_FACTURA*-1 ELSE 0 END AS VALOR_CREDT,	
						DESCRIPCION AS DESCRIPCION,
						DOCUMENTO AS DOCUMENTO 
					FROM CON.FACTURA FAC
					INNER JOIN CON.CMC_DOC AS CMC  ON (CMC.CMC = FAC.CMC AND CMC.TIPODOC = FAC.TIPO_DOCUMENTO) 
					WHERE DOCUMENTO = 'R0032227' --EGRESO_RECORD.DOCUMENTO
					 AND TIPO_DOCUMENTO = 'FAC'  --EGRESO_RECORD.TIPO_DOCUMENTO
					 AND FAC.REG_STATUS = ''
					 AND NIT = '9000742958'      --EGRESO_RECORD.NIT

					UNION ALL

					SELECT TIPO_DOCUMENTO,
						CODIGO_CUENTA_CONTABLE AS CUENTA,
						CASE WHEN VALOR_UNITARIO<0 THEN VALOR_UNITARIO*-1 ELSE 0 END AS VALOR_DEB,
						CASE WHEN VALOR_UNITARIO>0 THEN VALOR_UNITARIO ELSE 0 END AS  VALOR_CREDT,	
						DESCRIPCION AS DESCRIPCION,
						DOCUMENTO AS DOCUMENTO 
					FROM CON.FACTURA_DETALLE FAC
					WHERE DOCUMENTO = 'R0032227'  --EGRESO_RECORD.DOCUMENTO
					  AND TIPO_DOCUMENTO = 'FAC'  --EGRESO_RECORD.TIPO_DOCUMENTO
					  AND REG_STATUS = ''
					  AND NIT = '9000742958'       --EGRESO_RECORD.NIT 	
-- 						
			LOOP					

			IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('EGR_PRO','FAP', INFOITEMS_.CUENTA,'', 6)='S')THEN
				MCTYPE.MC_____FECHVENC__B = EGRESO_RECORD.FECHA_FACTURA; --FECHA VENCIMIENTO
					IF (EGRESO_RECORD.FECHA_VENCIMIENTO < EGRESO_RECORD.FECHA_FACTURA)THEN /** SE VALIDA SI LA FECHA DE VENCIMEINTO ES MENOR A LA DE CREACION*/
						MCTYPE.MC_____FECHEMIS__B = EGRESO_RECORD.FECHA_FACTURA; --FECHA CREACION
					ELSE 
						MCTYPE.MC_____FECHEMIS__B = EGRESO_RECORD.FECHA_FACTURA; --FECHA CREACION
					END IF;
			ELSE
				MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
				MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';
			END IF;

			
			FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(EGRESO_RECORD.FECHA_FACTURA,1,7),'-','') = EGRESO_RECORD.PERIODO THEN EGRESO_RECORD.FECHA_FACTURA::DATE ELSE CON.SP_FECHA_CORTE_MES(SUBSTRING(EGRESO_RECORD.PERIODO,1,4), SUBSTRING(EGRESO_RECORD.PERIODO,5,2)::INT)::DATE END;
			MCTYPE.MC_____FECHA_____B := CASE WHEN (EGRESO_RECORD.FECHA_FACTURA::DATE > FECHADOC_::DATE AND REPLACE(SUBSTRING(EGRESO_RECORD.FECHA_FACTURA,1,7),'-','') = EGRESO_RECORD.PERIODO)  THEN EGRESO_RECORD.FECHA_FACTURA::DATE ELSE FECHADOC_::DATE END; 
			MCTYPE.MC_____SECUINTE__DCD____B := SECUENCIA_INT;--SECUENCIA INTERNA
			MCTYPE.MC_____SECUINTE__B := SECUENCIA_INT;--SECUENCIA INTERNA
			MCTYPE.MC_____REFERENCI_B := EGRESO_RECORD.DOCUMENTO;  --'-'; --INFOITEMS_.NUM_OS; ---CAMBIAR A MULTISERVICIO...
			MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING( EGRESO_RECORD.PERIODO,1,4)::INT; 
			MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING( EGRESO_RECORD.PERIODO,5,2)::INT;
			MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF'; 
			MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('EGR_PRO', 'FAP', INFOITEMS_.CUENTA,'', 1); 
			MCTYPE.MC_____CODIGO____CU_____B := EGRESO_RECORD.CENTRO_COSTOS_INGRESO; --CON.OBTENER_HOMOLOGACION_APOTEOSYS('EGR_PRO', 'FAP', INFOITEMS_.CUENTA,'', 2); 
			MCTYPE.MC_____IDENTIFIC_TERCER_B := SUBSTRING(REPLACE(EGRESO_RECORD.NIT,'-',''),1,9);
			MCTYPE.MC_____DEBMONORI_B := 0; 
			MCTYPE.MC_____CREMONORI_B := 0;
			MCTYPE.MC_____DEBMONLOC_B := INFOITEMS_.VALOR_DEB::NUMERIC;
			MCTYPE.MC_____CREMONLOC_B := INFOITEMS_.VALOR_CREDT::NUMERIC;
			MCTYPE.MC_____INDTIPMOV_B := 4;
			MCTYPE.MC_____INDMOVREV_B := 'N';
			MCTYPE.MC_____OBSERVACI_B := EGRESO_RECORD.DOCUMENTO;  --INFOITEMS_.DESCRIPCION; --SUBSTRING((INFOITEMS_.NUM_OS ||' : '||INFOITEMS_.DESCRIPCION),1,249);
			MCTYPE.MC_____FECHORCRE_B := EGRESO_RECORD.FECHA_FACTURA::TIMESTAMP;
			MCTYPE.MC_____AUTOCREA__B := 'ADMIN';
			MCTYPE.MC_____FEHOULMO__B := EGRESO_RECORD.FECHA_FACTURA::TIMESTAMP;
			MCTYPE.MC_____AUTULTMOD_B := '';
			MCTYPE.MC_____VALIMPCON_B := 0;
			MCTYPE.MC_____NUMERO_OPER_B := '';
			MCTYPE.TERCER_CODIGO____TIT____B := INFOCLIENTE.TIPO_DOC;
			MCTYPE.TERCER_NOMBCORT__B := SUBSTRING(INFOCLIENTE.NOMBRE_CORTO,1,32);
			MCTYPE.TERCER_NOMBEXTE__B := SUBSTRING(INFOCLIENTE.NOMBRE,1,64);
			MCTYPE.TERCER_APELLIDOS_B := INFOCLIENTE.APELLIDOS;
			MCTYPE.TERCER_CODIGO____TT_____B := INFOCLIENTE.CODIGO;
			MCTYPE.TERCER_DIRECCION_B := CASE WHEN CHAR_LENGTH(INFOCLIENTE.DIRECCION)>64 THEN SUBSTR(INFOCLIENTE.DIRECCION,1,64) ELSE INFOCLIENTE.DIRECCION END;
			MCTYPE.TERCER_CODIGO____CIUDAD_B := INFOCLIENTE.CODIGOCIU;
			MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(INFOCLIENTE.TELEFONO)>15 THEN SUBSTR(INFOCLIENTE.TELEFONO,1,15) ELSE INFOCLIENTE.TELEFONO END;
			MCTYPE.TERCER_TIPOGIRO__B := 1;
			MCTYPE.TERCER_CODIGO____EF_____B := '';
			MCTYPE.TERCER_SUCURSAL__B := '';
			MCTYPE.TERCER_NUMECUEN__B := '';
			MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('EGR_PRO','FAP', INFOITEMS_.CUENTA,'', 3);
			MCTYPE.MC_____BASE______B:=0;

			IF(MCTYPE.MC_____FECHEMIS__B > MCTYPE.MC_____FECHA_____B) THEN
				MCTYPE.MC_____FECHEMIS__B :=  MCTYPE.MC_____FECHA_____B;
			END IF;

			--
			IF(INFOITEMS_.CUENTA = ANY (CUENTAS_IVA))THEN
				IF(INFOITEMS_.VALOR_CREDT>0) THEN
					MCTYPE.MC_____BASE______B:= INFOITEMS_.VALOR_CREDT/0.16;
				ELSE
					MCTYPE.MC_____BASE______B:= INFOITEMS_.VALOR_DEB/0.16;
				END IF;
			END IF;

			MCTYPE.MC_____NUMDOCSOP_B := EGRESO_RECORD.DOCUMENTO;

			-- IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL','NC', INFOITEMS_.CUENTA,'', 4)='S')THEN
-- 				MCTYPE.MC_____NUMDOCSOP_B := EGRESO_RECORD.DOCUMENTO;
-- 			ELSE
-- 				MCTYPE.MC_____NUMDOCSOP_B := '';
-- 			END IF;

			IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('EGR_PRO', 'FAP', INFOITEMS_.CUENTA,'', 5)::INT=1)THEN
				MCTYPE.MC_____NUMEVENC__B := 1;--NUMERO DE CUOTAS
			ELSE
				MCTYPE.MC_____NUMEVENC__B := NULL;
			END IF;
 			

			RAISE NOTICE 'NC ====>>>> %',INFOITEMS_.CUENTA;	
			SW:=CON.SP_INSERT_TABLE_MC_EGRE_PROV_PROVINT(MCTYPE);
			SECUENCIA_INT :=SECUENCIA_INT+1;		

		END LOOP;

		RAISE NOTICE '<<<<==== TERMINO ====>>>> %',EGRESO_RECORD.DOCUMENTO;

		--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
		IF CON.SP_VALIDACIONES(MCTYPE,'FAC_CC') = 'N' THEN 
			SW = 'N';
			CONTINUE; 
		END IF;			

		IF(SW = 'S')THEN
						
			UPDATE 
				FACTURA 
			SET 
				PROCESADO='S' 
			WHERE 
				DOCUMENTO = EGRESO_RECORD.DOCUMENTO 
				AND TIPO_DOCUMENTO = EGRESO_RECORD.TIPO_DOCUMENTO
				AND NIT = EGRESO_RECORD.NIT;
		
		END IF;

	END LOOP;
	
RETURN 'OK';

END
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_sl_egreso_pago_prov_provint_apoteosys()
  OWNER TO postgres;
