SELECT NUMBER_RECORDS_MC_EGRE_PROV_PROVINT('201701') AS REGISTROS_TABLA_TRASLADO;

SELECT *
FROM CON.FACTURA FAC
WHERE DOCUMENTO = 'R0034201'
AND TIPO_DOCUMENTO = 'FAC'

-- UPDATE CON.FACTURA
-- SET PROCESADO = 'S'
-- WHERE DOCUMENTO = 'R0032227'
-- AND TIPO_DOCUMENTO = 'FAC'

SELECT * FROM CON.FACTURA_DETALLE
WHERE DOCUMENTO = '900074295'

--SELECT * FROM CON.FACTURA WHERE DOCUMENTO = 'R0032372' AND TIPO_DOCUMENTO = 'FAC';
--SELECT CMC, COUNT(*) FROM CON.FACTURA WHERE CMC != 'PO' GROUP BY CMC ORDER BY CMC

--SELECT * FROM CON.MC_EGRE_PROV_PROVINT WHERE MC_____CODIGO____CD_____B='IN'

SELECT TIPO_DOCUMENTO,
	CMC.CUENTA AS CUENTA,
	CASE WHEN VALOR_FACTURA>0 THEN VALOR_FACTURA ELSE 0 END AS VALOR_DEB ,	
	CASE WHEN VALOR_FACTURA<0 THEN VALOR_FACTURA*-1 ELSE 0 END AS VALOR_CREDT,	
	DESCRIPCION AS DESCRIPCION,
	DOCUMENTO AS DOCUMENTO 
FROM CON.FACTURA FAC
INNER JOIN CON.CMC_DOC AS CMC  ON (CMC.CMC = 'PO' AND CMC.TIPODOC = 'FAC') 
WHERE DOCUMENTO = 'R0032250' --EGRESO_RECORD.DOCUMENTO --R0032227' --
AND TIPO_DOCUMENTO = 'FAC'
AND FAC.REG_STATUS = ''
AND NIT = '9000742958' --'9000742958'      --

UNION ALL

SELECT TIPO_DOCUMENTO,
	CODIGO_CUENTA_CONTABLE AS CUENTA,
	CASE WHEN VALOR_UNITARIO<0 THEN VALOR_UNITARIO*-1 ELSE 0 END AS VALOR_DEB,
	CASE WHEN VALOR_UNITARIO>0 THEN VALOR_UNITARIO ELSE 0 END AS  VALOR_CREDT,	
	DESCRIPCION AS DESCRIPCION,
	DOCUMENTO AS DOCUMENTO 
FROM CON.FACTURA_DETALLE FAC
WHERE DOCUMENTO = 'R0032250' --'R0032227'  --
AND TIPO_DOCUMENTO = 'FAC'  --
AND REG_STATUS = ''
AND NIT = '9000742958'       -- 	


SELECT CON.OBTENER_HOMOLOGACION_APOTEOSYS('EGR_FIN', 'FAP', '11100121','',1);
'11050503'
'11050510'


SELECT * FROM CON.HOMOLACION_INTERFACE WHERE CUENTA_FINTRA = '11050510' AND TIPO_DOC_FINTRA = 'EGR_FIN'





