Select 1 + 1; 

--
SELECT * 
FROM   TEM.TRASLADO_CXP_CONTRATISTAS_FINTRA_SELECTRIK 
WHERE  HANDLE_CODE = 'CD' 
AND  TIPO_DOCUMENTO = 'FAP'
AND  PERIODO   = '201703'
--AND  PROVEEDOR = FACTURA_NM.NIT
--AND  DOCUMENTO = FACTURA_NM.DOCUMENTO


/*
DELETE FROM TEM.TRASLADO_CXP_CONTRATISTAS_FINTRA_SELECTRIK 
WHERE  HANDLE_CODE = 'CD' 
AND    TIPO_DOCUMENTO = 'FAP'
AND    PERIODO   = '201701'
*/
--AND  PROVEEDOR = FACTURA_NM.NIT
--AND  DOCUMENTO = FACTURA_NM.DOCUMENTO


--
SELECT * FROM CON.MC_DOC_CXP_CONT_FIN;
--TRUNCATE TABLE CON.MC_DOC_CXP_CONT_FIN    