SELECT  
	EGRE.TIPO_DOCUMENTO,
	--COALESCE((SELECT CODIGO_CUENTA FROM BANCO  WHERE BRANCH_CODE =EGRE.BRANCH_CODE AND BANK_ACCOUNT_NO=EGRE.BANK_ACCOUNT_NO),'00000000') AS CUENTA,
	CMC.CUENTA AS CUENTA,
	--'22050801'::TEXT AS CUENTA,
	''::TEXT AS PROVEEDOR,
	CASE WHEN EGRE.VLR>0 THEN EGRE.VLR ELSE 0 END AS  VALOR_DEB ,
	CASE WHEN EGRE.VLR<0 THEN EGRE.VLR*-1 ELSE 0 END AS VALOR_CREDT,
	EGRE.DESCRIPTION,
	EGRE.DOCUMENTO
FROM EGRESODET AS EGRE
INNER JOIN CON.CMC_DOC AS CMC ON (CMC.TIPODOC=EGRE.TIPO_DOCUMENTO AND  'CD'=CMC.CMC)
WHERE DOCUMENTO =  'MS00361'
 AND DOCUMENT_NO = 'BC976'
 AND EGRE.DESCRIPTION LIKE 'CXP CONTRATISTA%'
 AND TIPO_DOCUMENTO = 'FAP'
 AND BRANCH_CODE = 'CAJA TESORERIA'
 AND BANK_ACCOUNT_NO = 'CAJA'

UNION ALL

SELECT  
	EGRE.TIPO_DOCUMENTO,
	COALESCE((SELECT CODIGO_CUENTA FROM BANCO  WHERE BRANCH_CODE =EGRE.BRANCH_CODE AND BANK_ACCOUNT_NO=EGRE.BANK_ACCOUNT_NO),'00000000') AS CUENTA,
	''::TEXT AS PROVEEDOR,
	CASE WHEN EGRE.VLR<0 THEN EGRE.VLR*-1 ELSE 0 END AS VALOR_DEB,
	CASE WHEN EGRE.VLR>0 THEN EGRE.VLR ELSE 0 END AS  VALOR_CREDT,
	'BANCOS':: TEXT AS DESCRIPCION,	
	EGRE.DOCUMENT_NO AS DOCUMENTO
FROM EGRESODET AS EGRE
WHERE DOCUMENTO =  'MS00361'
 AND DOCUMENT_NO = 'BC976'
 AND EGRE.DESCRIPTION LIKE 'CXP CONTRATISTA%'
 AND TIPO_DOCUMENTO = 'FAP'
 AND BRANCH_CODE = 'CAJA TESORERIA'
 AND BANK_ACCOUNT_NO = 'CAJA'

--SELECT * FROM EGRESODET LIMIT 1;
--SELECT * FROM CON.CMC_DOC WHERE CUENTA = '22050801'

--TABLA DE CONTROL
--TRUNCATE tem.traslado_egreso_contratistas_fintra;
SELECT * FROM tem.traslado_egreso_contratistas_fintra;

--TABLA DE TRASLADO HACIA APOTEOSYS
SELECT 
	* 
FROM CON.MC_DOC_CXP_CONT_FIN 
WHERE MC_____CODIGO____CD_____B   = 'EGRC' AND
MC_____CODIGO____TD_____B = 'EGRN';







