-- Function: con.interfaz_sl_contratista_cc_selectrik_apoteosys()

-- DROP FUNCTION con.interfaz_sl_contratista_cc_selectrik_apoteosys();

CREATE OR REPLACE FUNCTION con.interfaz_sl_contratista_cc_selectrik_apoteosys()
  RETURNS text AS
$BODY$


DECLARE

 /************************************************
  *DESCRIPCION: 
  *AUTOR		:=		@WSIADO	
  *FECHA CREACION	:=		2018-01-09
  *LAST_UPDATE		:=	 	
  *DESCRIPCION DE CAMBIOS Y FECHA
  ************************************************/

_DOC RECORD;
INFOITEMS_ RECORD;
INFOCLIENTE RECORD;
LONGITUD NUMERIC;
SECUENCIA_GEN INTEGER;
SECUENCIA_INT INTEGER:= 1;
CUENTAS_IVA VARCHAR[] := '{}';
FECHADOC_ VARCHAR:= '';
MCTYPE CON.TYPE_INSERT_MC;
SW TEXT:='N';
VALIDACIONES TEXT;
CUOTA_INICIAL VARCHAR;
_EXISTE CHARACTER VARYING :='';

BEGIN
	/**SACAMOS EL LISTADO DE NM*/
	FOR _DOC IN 
	
		SELECT 
			A.TIPO_DOCUMENTO, 
			A.FECHA_DOCUMENTO AS FECHA_FACTURA,
			A.FECHA_VENCIMIENTO,
			A.PERIODO,
			A.PROVEEDOR AS NIT,
			C.ID_SOLICITUD,
			C.CENTRO_COSTOS_INGRESO,
			C.CENTRO_COSTOS_GASTOS,
			A.DESCRIPCION,
			C.NUM_OS,
			A.DOCUMENTO
			 
			--A.BANCO , 
			--A.FECHA_DOCUMENTO,
		FROM FIN.CXP_DOC 		AS A
		INNER JOIN PROVEEDOR 		AS PRV  ON (A.PROVEEDOR=PRV.NIT)
		INNER JOIN OPAV.ACCIONES 	AS B	ON (A.REFERENCIA_1 = B.ID_ACCION)
		INNER JOIN OPAV.OFERTAS 	AS C	ON (B.ID_SOLICITUD = C.ID_SOLICITUD)
		WHERE 
			TIPO_DOCUMENTO		=	'FAP' 
			AND HANDLE_CODE		=	'CI' 
			AND PERIODO		=	'201711'
			AND A.REG_STATUS	=	''
			AND C.CENTRO_COSTOS_INGRESO !=  ''
			AND DOCUMENTO 		LIKE 	'CC%'
			--AND COALESCE(PROCESADO, 'N' ) = 'N'

		
	LOOP


	-- 	raise notice 'NIT : %',_DOC.NIT;
-- 		/*====SE VERIFICA SI EL PROVEEDOR EXISTE=====*/
-- 		SELECT INTO _EXISTE COALESCE((SELECT 'SI'::VARCHAR FROM PROVEEDOR WHERE NIT = _DOC.NIT),'NO');
-- 			raise notice '_EXISTE : %',_EXISTE;
-- 			IF(_EXISTE = 'NO' )THEN
-- 				INSERT INTO TEM.SL_PROVEEDORES_INEXISTENTE(DOCUMENTO , PROVEEDOR , CREATION_DATE , CREATION_USER) VALUES (_DOC.DOCUMENTO , _DOC.NIT , NOW(), 'WSIADO');
-- 				CONTINUE;
-- 			ELSE
-- 				SELECT INTO INFOCLIENTE
-- 						'NIT' AS TIPO_DOC,
-- 						(CASE 
-- 						WHEN GRAN_CONTRIBUYENTE ='N' AND AGENTE_RETENEDOR ='N' THEN 'RCOM' 
-- 						WHEN GRAN_CONTRIBUYENTE ='N' AND AGENTE_RETENEDOR ='S' THEN 'RCAU' 
-- 						WHEN GRAN_CONTRIBUYENTE ='S' AND AGENTE_RETENEDOR ='N' THEN 'GCON' 
-- 						WHEN GRAN_CONTRIBUYENTE ='S' AND AGENTE_RETENEDOR ='S' THEN 'GCAU'
-- 						ELSE 'PNAL' END) AS CODIGO,
-- 						'08001'AS CODIGOCIU,
-- 						COALESCE((D.NOMBRE1||' '||D.NOMBRE2),PAYMENT_NAME) AS NOMBRE_CORTO, 
-- 						PAYMENT_NAME AS  NOMBRE,
-- 						(D.APELLIDO1||' '||D.APELLIDO2) AS APELLIDOS,
-- 						COALESCE(DIRECCION, '-' ) as DIRECCION,
-- 						COALESCE(TELEFONO, '-') AS TELEFONO
-- 						
-- 					FROM PROVEEDOR PROV
-- 					LEFT JOIN NIT D ON(D.CEDULA=PROV.NIT)
-- 					LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
-- 					WHERE NIT =  _DOC.NIT;	
-- 			END IF;


		SELECT INTO INFOCLIENTE
			'NIT' AS TIPO_DOC,
			(CASE 
			WHEN GRAN_CONTRIBUYENTE ='N' AND AGENTE_RETENEDOR ='N' THEN 'RCOM' 
			WHEN GRAN_CONTRIBUYENTE ='N' AND AGENTE_RETENEDOR ='S' THEN 'RCAU' 
			WHEN GRAN_CONTRIBUYENTE ='S' AND AGENTE_RETENEDOR ='N' THEN 'GCON' 
			WHEN GRAN_CONTRIBUYENTE ='S' AND AGENTE_RETENEDOR ='S' THEN 'GCAU'
			ELSE 'PNAL' END) AS CODIGO,
			'08001'AS CODIGOCIU,
			COALESCE((D.NOMBRE1||' '||D.NOMBRE2),PAYMENT_NAME) AS NOMBRE_CORTO, 
			PAYMENT_NAME AS  NOMBRE,
			(D.APELLIDO1||' '||D.APELLIDO2) AS APELLIDOS,
			COALESCE(DIRECCION, '-' ) as DIRECCION,
			COALESCE(TELEFONO, '-') AS TELEFONO
			
		FROM PROVEEDOR PROV
		LEFT JOIN NIT D ON(D.CEDULA=PROV.NIT)
		LEFT JOIN CIUDAD E ON(E.CODCIU=D.CODCIU)
		WHERE NIT =  _DOC.NIT;	
			
					
		
		----SECUENCIA GENERAL
		SELECT INTO SECUENCIA_GEN  NEXTVAL('CON.INTERFAZ_SECUENCIA_CXP_APOTEOSYS');
		
	

		MCTYPE.MC_____CODIGO____CONTAB_B := 'SELE'; 
		MCTYPE.MC_____CODIGO____TD_____B := 'CXPN'; 
		MCTYPE.MC_____CODIGO____CD_____B := 'CCSL'; 
		MCTYPE.MC_____NUMERO____B := SECUENCIA_GEN; --SECUENCIA GENERAL
		
		--MCTYPE.MC_____CODIGO____TD_____B --tipo documento
		--MCTYPE.MC_____CODIGO____CD_____B --concepto
		
		
		/**BUSCAMOS LA INFORMACION COMPLETA QUE CONFORMARA EL ASIENTO CONTABLE PARA MANDARLO A APOTEOSYS*/
		FOR INFOITEMS_ IN 		
		       

			SELECT
						TIPO_DOCUMENTO,
						CODIGO_CUENTA AS CUENTA,
						PROVEEDOR,
						CASE WHEN VLR>0 THEN VLR ELSE 0 END AS  VALOR_DEB, 
						CASE WHEN VLR<0 THEN VLR*-1 ELSE 0 END AS VALOR_CREDT,
						DESCRIPCION
			FROM 
						FIN.CXP_ITEMS_DOC
			WHERE TIPO_DOCUMENTO='FAP' AND 
						DOCUMENTO =_DOC.DOCUMENTO
			UNION ALL
			SELECT
						TIPO_DOCUMENTO,
						'23200101' AS CUENTA,
						PROVEEDOR,
						0 AS VALOR_DEB,
						VLR_NETO AS VALOR_CREDT,
						DESCRIPCION				
			FROM 
						FIN.CXP_DOC 
			WHERE TIPO_DOCUMENTO='FAP' 
				AND DOCUMENTO =_DOC.DOCUMENTO

		LOOP			
			
			IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL','FAP', INFOITEMS_.CUENTA,'', 6)='S')THEN
				IF(_DOC.FECHA_VENCIMIENTO::DATE>NOW()::DATE)THEN
					_DOC.FECHA_VENCIMIENTO = NOW()::DATE;
				END IF; 
				MCTYPE.MC_____FECHVENC__B = _DOC.FECHA_VENCIMIENTO; --FECHA VENCIMIENTO
					IF (_DOC.FECHA_VENCIMIENTO < _DOC.FECHA_FACTURA)THEN /** SE VALIDA SI LA FECHA DE VENCIMEINTO ES MENOR A LA DE CREACION*/
						MCTYPE.MC_____FECHEMIS__B = _DOC.FECHA_VENCIMIENTO; --FECHA CREACION
					ELSE 
						MCTYPE.MC_____FECHEMIS__B = _DOC.FECHA_FACTURA; --FECHA CREACION
					END IF;
			ELSE
				MCTYPE.MC_____FECHEMIS__B='0099-01-01 00:00:00';
				MCTYPE.MC_____FECHVENC__B='0099-01-01 00:00:00';
			END IF;

			
			FECHADOC_ := CASE WHEN REPLACE(SUBSTRING(_DOC.FECHA_FACTURA,1,7),'-','') = _DOC.PERIODO THEN _DOC.FECHA_FACTURA::DATE ELSE CON.SP_FECHA_CORTE_MES(SUBSTRING(_DOC.PERIODO,1,4), SUBSTRING(_DOC.PERIODO,5,2)::INT)::DATE END;
			MCTYPE.MC_____FECHA_____B := CASE WHEN (_DOC.FECHA_FACTURA::DATE > FECHADOC_::DATE AND REPLACE(SUBSTRING(_DOC.FECHA_FACTURA,1,7),'-','') = _DOC.PERIODO)  THEN _DOC.FECHA_FACTURA::DATE ELSE FECHADOC_::DATE END; 
			MCTYPE.MC_____SECUINTE__DCD____B := SECUENCIA_INT;--SECUENCIA INTERNA
			MCTYPE.MC_____SECUINTE__B := SECUENCIA_INT;--SECUENCIA INTERNA
			MCTYPE.MC_____REFERENCI_B := _DOC.NUM_OS; ---CAMBIAR A MULTISERVICIO...
			MCTYPE.MC_____CODIGO____PF_____B := SUBSTRING( _DOC.PERIODO,1,4)::INT; 
			MCTYPE.MC_____NUMERO____PERIOD_B := SUBSTRING( _DOC.PERIODO,5,2)::INT;
			MCTYPE.MC_____CODIGO____PC_____B :=  'PUCF'; 
			MCTYPE.MC_____CODIGO____CPC____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL', 'FAP', INFOITEMS_.CUENTA,'', 1); 
			MCTYPE.MC_____CODIGO____CU_____B := _DOC.CENTRO_COSTOS_INGRESO;
			MCTYPE.MC_____IDENTIFIC_TERCER_B := SUBSTRING(REPLACE(_DOC.NIT,'-',''),1,9);
			MCTYPE.MC_____DEBMONORI_B := 0; 
			MCTYPE.MC_____CREMONORI_B := 0;
			MCTYPE.MC_____DEBMONLOC_B := INFOITEMS_.VALOR_DEB::NUMERIC;
			MCTYPE.MC_____CREMONLOC_B := INFOITEMS_.VALOR_CREDT::NUMERIC;
			MCTYPE.MC_____INDTIPMOV_B := 4;
			MCTYPE.MC_____INDMOVREV_B := 'N';
			MCTYPE.MC_____OBSERVACI_B := SUBSTRING(INFOITEMS_.DESCRIPCION,1,249);
			MCTYPE.MC_____FECHORCRE_B := _DOC.FECHA_FACTURA::TIMESTAMP;
			MCTYPE.MC_____AUTOCREA__B := 'ADMIN';
			MCTYPE.MC_____FEHOULMO__B := _DOC.FECHA_FACTURA::TIMESTAMP;
			MCTYPE.MC_____AUTULTMOD_B := '';
			MCTYPE.MC_____VALIMPCON_B := 0;
			MCTYPE.MC_____NUMERO_OPER_B := '';
			MCTYPE.TERCER_CODIGO____TIT____B := INFOCLIENTE.TIPO_DOC;
			MCTYPE.TERCER_NOMBCORT__B := SUBSTRING(INFOCLIENTE.NOMBRE_CORTO,1,32);
			MCTYPE.TERCER_NOMBEXTE__B := SUBSTRING(INFOCLIENTE.NOMBRE,1,64);
			MCTYPE.TERCER_APELLIDOS_B := INFOCLIENTE.APELLIDOS;
			MCTYPE.TERCER_CODIGO____TT_____B := INFOCLIENTE.CODIGO;
			MCTYPE.TERCER_DIRECCION_B := CASE WHEN CHAR_LENGTH(INFOCLIENTE.DIRECCION)>64 THEN SUBSTR(INFOCLIENTE.DIRECCION,1,64) ELSE INFOCLIENTE.DIRECCION END;
			MCTYPE.TERCER_CODIGO____CIUDAD_B := INFOCLIENTE.CODIGOCIU;
			MCTYPE.TERCER_TELEFONO1_B := CASE WHEN CHAR_LENGTH(INFOCLIENTE.TELEFONO)>15 THEN SUBSTR(INFOCLIENTE.TELEFONO,1,15) ELSE INFOCLIENTE.TELEFONO END;
			MCTYPE.TERCER_TIPOGIRO__B := 1;
			MCTYPE.TERCER_CODIGO____EF_____B := '';
			MCTYPE.TERCER_SUCURSAL__B := '';
			MCTYPE.TERCER_NUMECUEN__B := '';
			MCTYPE.MC_____CODIGO____DS_____B := CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL','FAP', INFOITEMS_.CUENTA,'', 3);
			MCTYPE.MC_____BASE______B:=0;

			IF(MCTYPE.MC_____FECHEMIS__B > MCTYPE.MC_____FECHA_____B) THEN
				MCTYPE.MC_____FECHEMIS__B :=  MCTYPE.MC_____FECHA_____B;
			END IF;

			IF(INFOITEMS_.VALOR_CREDT= 0)THEN
				IF(INFOITEMS_.VALOR_CREDT)THEN
					CONTINUE; 
				END IF;
			END IF;
					
			IF(INFOITEMS_.CUENTA = ANY (CUENTAS_IVA))THEN
				IF(INFOITEMS_.VALOR_CREDT>0) THEN
					MCTYPE.MC_____BASE______B:= INFOITEMS_.VALOR_CREDT/0.19;
				ELSE
					MCTYPE.MC_____BASE______B:= INFOITEMS_.VALOR_DEB/0.19;
				END IF;
			END IF;

			MCTYPE.MC_____NUMDOCSOP_B := _DOC.DOCUMENTO;

			-- IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL','FAP', INFOITEMS_.CUENTA,'', 4)='S')THEN
-- 				MCTYPE.MC_____NUMDOCSOP_B := _DOC.DOCUMENTO;
-- 			ELSE
-- 				MCTYPE.MC_____NUMDOCSOP_B := '';
-- 			END IF;

			IF(CON.OBTENER_HOMOLOGACION_APOTEOSYS('CXP_SEL', 'FAP', INFOITEMS_.CUENTA,'', 5)::INT=1)THEN
				MCTYPE.MC_____NUMEVENC__B := 1;--NUMERO DE CUOTAS
			ELSE
				MCTYPE.MC_____NUMEVENC__B := NULL;
			END IF;		

 			
			RAISE NOTICE 'CC ====>>>> %',INFOITEMS_.CUENTA;	
			SW := CON.SP_INSERT_TABLE_MC_SL_FAC_CC_SEL(MCTYPE);
			SECUENCIA_INT :=SECUENCIA_INT+1;
		
		END LOOP;

		RAISE NOTICE '<<<<==== TERMINO ====>>>> %',_DOC.DOCUMENTO;


		--VALIDAMOS VALORES DEBITOS Y CREDITOS DEL COMPROBANTE A TRASLADAR.
		IF CON.SP_VALIDACIONES_SEL(MCTYPE,'FAC_CC') ='N' THEN 
			SW = 'N';
			CONTINUE; 
		END IF;	
		
		IF(SW = 'S')THEN
			UPDATE  FIN.CXP_DOC  SET PROCESADO = 'S' WHERE DOCUMENTO  = _DOC.DOCUMENTO AND TIPO_DOCUMENTO = 'FAP' AND HANDLE_CODE =	'CI' ;
		END IF;

		SECUENCIA_INT:=1;
		
	END LOOP;


RETURN 'OK';
	
END;
$BODY$
  LANGUAGE plpgsql VOLATILE;
ALTER FUNCTION con.interfaz_sl_contratista_cc_selectrik_apoteosys()
  OWNER TO postgres;

select con.interfaz_sl_contratista_cc_selectrik_apoteosys();

--TRUNCATE TABLE CON.MC_SL_FAC_CC_SEL;

SELECT tercer_nombexte__b,COUNT(0) FROM  CON.MC_SL_FAC_CC_SEL WHERE PROCESADO='N' GROUP BY tercer_nombexte__b ;