
---------------------------------------------------------------------------
---------------------------------------------------------------------------
SELECT SUM(VALOR_CREDT) as credito , SUM(VALOR_DEB) as debito FROM (
SELECT  A.TIPO_DOCUMENTO,
		A.CODIGO_CUENTA AS CUENTA,	
		A.PROVEEDOR,				
		CASE WHEN A.VLR>0 THEN A.VLR ELSE 0 END AS VALOR_DEB,						
		CASE WHEN A.VLR<0 THEN A.VLR*-1 ELSE 0 END AS VALOR_CREDT,					
		A.DESCRIPCION,
		CCS.ID_SOLICITUD,
		CCS.CENTRO_COSTOS_INGRESO,
		CCS.CENTRO_COSTOS_GASTOS,
		CCS.NUM_OS
	FROM 
		FIN.CXP_ITEMS_DOC A
	INNER JOIN FIN.CXP_DOC B ON(B.DSTRCT=A.DSTRCT AND B.TIPO_DOCUMENTO=A.TIPO_DOCUMENTO AND B.PROVEEDOR=A.PROVEEDOR AND B.DOCUMENTO=A.DOCUMENTO)
	INNER JOIN sl_centro_costos_selectrik_dblink AS CCS     ON (A.REFERENCIA_1 = CCS.ID_ACCION )
	WHERE       A.TIPO_DOCUMENTO		= 	'FAP'
		AND B.HANDLE_CODE		=	'CD'
		AND A.DOCUMENTO 		=	'278'
		AND A.CODIGO_CUENTA IN('28151001','28151006'))K
		
UNION ALL


SELECT SUM(VALOR_CREDT) as credito , SUM(VALOR_DEB) as debito FROM (
SELECT  A.TIPO_DOCUMENTO,
	A.CODIGO_CUENTA AS CUENTA,	
	A.PROVEEDOR,				
	CASE WHEN A.VLR>0 THEN A.VLR ELSE 0 END AS VALOR_DEB ,						
	CASE WHEN A.VLR<0 THEN A.VLR*-1 ELSE 0 END AS VALOR_CREDT,					
	A.DESCRIPCION,
	CCS.ID_SOLICITUD,
	CCS.CENTRO_COSTOS_INGRESO,
	CCS.CENTRO_COSTOS_GASTOS,
	CCS.NUM_OS
FROM 
	FIN.CXP_ITEMS_DOC A
INNER JOIN FIN.CXP_DOC B ON(B.DSTRCT=A.DSTRCT AND B.TIPO_DOCUMENTO=A.TIPO_DOCUMENTO AND B.PROVEEDOR=A.PROVEEDOR AND B.DOCUMENTO=A.DOCUMENTO)
INNER JOIN sl_centro_costos_selectrik_dblink AS CCS     ON (A.REFERENCIA_1 = CCS.ID_ACCION )
WHERE 	A.TIPO_DOCUMENTO		= 	'FAP'
	AND B.HANDLE_CODE		=	'CD'
	AND A.DOCUMENTO 		=	'278'
	AND A.CODIGO_CUENTA 		IN	('28151002','I010120064194','I010120064195','22050801')
	--AND DESCRIPCION LIKE  'CXP CONTRATISTA%')
	

UNION ALL

--SELECT SUM(VALOR_CREDT) as credito , SUM(VALOR_DEB) as debito FROM (
SELECT  	A.TIPO_DOCUMENTO,
		'22050801' AS CUENTA,	
		A.PROVEEDOR,				
		0 AS VALOR_DEB,						
		sum(vlr) AS VALOR_CREDT,					
		'CXP CONTRATISTA' as DESCRIPCION,
		CCS.ID_SOLICITUD,
		CCS.CENTRO_COSTOS_INGRESO,
		CCS.CENTRO_COSTOS_GASTOS,
		CCS.NUM_OS
	FROM 
		FIN.CXP_ITEMS_DOC A
	INNER JOIN FIN.CXP_DOC B ON(B.DSTRCT=A.DSTRCT AND B.TIPO_DOCUMENTO=A.TIPO_DOCUMENTO AND B.PROVEEDOR=A.PROVEEDOR AND B.DOCUMENTO=A.DOCUMENTO)
	INNER JOIN CON.CMC_DOC  AS CMC  ON (CMC.TIPODOC=b.TIPO_DOCUMENTO AND  b.HANDLE_CODE=CMC.CMC)
	INNER JOIN sl_centro_costos_selectrik_dblink AS CCS     ON (A.REFERENCIA_1 = CCS.ID_ACCION )
	WHERE       A.TIPO_DOCUMENTO		= 	'FAP'
		AND B.HANDLE_CODE		=	'CD'
		AND A.DOCUMENTO 		=	'278'
		AND A.CODIGO_CUENTA IN('28151001','28151006','28151002','I010120064194','I010120064195')
	GROUP BY 
		A.TIPO_DOCUMENTO,
		A.PROVEEDOR,				
		CCS.ID_SOLICITUD,
		CCS.CENTRO_COSTOS_INGRESO,
		CCS.CENTRO_COSTOS_GASTOS,
		CCS.NUM_OS

	

) P
