--Crear concepto Paso 7
--Homologar la(s( cuenta(s)



-- SELECT REFERENCIA_1 FROM FIN.CXP_ITEMS_DOC WHERE DOCUMENTO =  'T00000507'--FACTURA_NM.DOCUMENTO  
-- AND  CODIGO_CUENTA='11050524';

--DOCUMENTOS POR CONCEPTO
--DELETE FROM CON.MC_SL_FAC_CC_SEL   WHERE MC_____CODIGO____CD_____B = 'CPFI' AND MC_____NUMERO____PERIOD_B IN (5,6,7,8,9,10,11,12)          AND MC_____CODIGO____CU_____B = '';
--SELECT * FROM CON.MC_SL_FAC_CC_SEL WHERE MC_____CODIGO____CD_____B = 'CPFI' AND MC_____NUMERO____PERIOD_B IN (4)      AND PROCESADO  = 'R' 

--SELECT DOCUMENTO FROM FIN.CXP_DOC WHERE DOCUMENTO IN ('T00000747');

--SELECT * FROM FIN.CXP_ITEMS_DOC WHERE DOCUMENTO = 'T00000505' AND  CODIGO_CUENTA = '11050524';

--Paso 6 Query Detalle
SELECT 
        'T00000507' AS DOCUMENTO,--TT.DOCUMENTO,
	T1.TIPO_DOCUMENTO,
	T1.CODIGO_CUENTA AS CUENTA,	
	T1.PROVEEDOR,	
	T1.ID_ACCION,
	T1.NUM_OS,	
	T1.CENTRO_COSTOS_INGRESO,
	T1.CENTRO_COSTOS_GASTOS,
	T1.VLR-((T1.VLR*(T1.TOTAL_DESCUENTO_FACTORING/100))) AS VALOR_DEB,
        0.00::NUMERIC AS VALOR_CREDT,
	UPPER(T1.DESCRIPCION)AS  DESCRIPCION
      FROM (
      SELECT CXP.PROVEEDOR,
             CXP.TIPO_DOCUMENTO,
             CXP.DOCUMENTO,
             'CANCELA FACTURA CONTRATISTA POR TRASLADO A FINTRA : '||ACC.ID_ACCION AS DESCRIPCION,
             (SUM(CXPDET.VLR)) AS VLR,
             CXPDET.CODIGO_CUENTA,
             ACC.ID_ACCION,
             OFER.NUM_OS, 
             OFER.CENTRO_COSTOS_INGRESO,
             OFER.CENTRO_COSTOS_GASTOS,
             ACC.POR_FACTORING_CONTRATISTA,
             ACC.POR_FORMULA_CONTRATISTA,
             (ACC.POR_FACTORING_CONTRATISTA+ACC.POR_FORMULA_CONTRATISTA) AS TOTAL_DESCUENTO_FACTORING,
             CXP.FECHA_DOCUMENTO,
             CXP.FECHA_VENCIMIENTO           
      FROM FIN.CXP_ITEMS_DOC CXPDET
      INNER JOIN FIN.CXP_DOC CXP ON (CXP.DOCUMENTO=CXPDET.DOCUMENTO AND CXP.TIPO_DOCUMENTO=CXPDET.TIPO_DOCUMENTO AND CXP.PROVEEDOR=CXPDET.PROVEEDOR)
      INNER JOIN OPAV.ACCIONES ACC ON (ACC.ID_ACCION=CXPDET.REFERENCIA_1 AND ACC.REG_STATUS!='A')
      INNER JOIN OPAV.OFERTAS AS OFER ON (ACC.ID_SOLICITUD = OFER.ID_SOLICITUD)
      INNER JOIN PROVEEDOR AS PRV  ON (CXP.PROVEEDOR=PRV.NIT)
      WHERE 
      CXP.DOCUMENTO= '278'--FACTURA_NM.DOCUMENTO   ---?
      --AND CXP.PROVEEDOR = FACTURA_NM.NIT ---?
      AND CXP.TIPO_DOCUMENTO='FAP' 
      AND CXP.HANDLE_CODE ='CD' 
      AND CXP.DESCRIPCION LIKE 'Reunifica facturas internas:%'
      AND COALESCE(PROCESADO,'N')  = 'S' 
      GROUP BY 
      CXP.PROVEEDOR,
      CXP.TIPO_DOCUMENTO,
      CXP.DOCUMENTO,
      CXPDET.CODIGO_CUENTA,
      ACC.ID_ACCION, 
      ACC.POR_FACTORING_CONTRATISTA,
      ACC.POR_FORMULA_CONTRATISTA,
      OFER.CENTRO_COSTOS_INGRESO,
      OFER.CENTRO_COSTOS_GASTOS,
      OFER.NUM_OS,
      CXP.FECHA_DOCUMENTO,
      CXP.FECHA_VENCIMIENTO
      
     )T1
UNION ALL
SELECT 
	'T00000507' AS DOCUMENTO,--TT.DOCUMENTO,
	CXP.TIPO_DOCUMENTO,
	CXPDET.CODIGO_CUENTA AS CUENTA,	
	CXP.PROVEEDOR,	
	ACC.ID_ACCION,
	OFER.NUM_OS,	
	OFER.CENTRO_COSTOS_INGRESO,
	OFER.CENTRO_COSTOS_GASTOS,
	SUM(CXPDET.VLR) AS VALOR_DEB,
	0::NUMERIC AS VALOR_CREDT,
	UPPER(CXPDET.DESCRIPCION)AS  DESCRIPCION
	--CXPDET.*
FROM FIN.CXP_ITEMS_DOC CXPDET
INNER JOIN FIN.CXP_DOC CXP ON (CXPDET.DOCUMENTO =CXP.DOCUMENTO AND CXPDET.TIPO_DOCUMENTO=CXP.TIPO_DOCUMENTO )
LEFT JOIN OPAV.ACCIONES ACC ON (ACC.ID_ACCION=CXPDET.REFERENCIA_1 AND ACC.REG_STATUS!='A')
LEFT JOIN OPAV.OFERTAS AS OFER	ON (ACC.ID_SOLICITUD = OFER.ID_SOLICITUD)
WHERE CXP.TIPO_DOCUMENTO= 'FAP'--FACTURA_NM.TIPO_DOCUMENTO
AND   CXP.HANDLE_CODE = 'TF'
AND   CXP.DOCUMENTO 	= 'T00000507' --FACTURA_NM.DOCUMENTO
AND   CXPDET.CODIGO_CUENTA != '11050524'
--AND   CXP.REG_STATUS		=''
GROUP BY 
      CXPDET.CODIGO_CUENTA, 
      CXPDET.DESCRIPCION,
      CXP.DOCUMENTO, 
      CXP.TIPO_DOCUMENTO,	
      CXP.PROVEEDOR,	
      ACC.ID_ACCION,
      OFER.NUM_OS,	
      OFER.CENTRO_COSTOS_INGRESO,
      OFER.CENTRO_COSTOS_GASTOS

UNION ALL

SELECT
	'T00000507' AS DOCUMENTO,--TT.DOCUMENTO,
	TT.TIPO_DOCUMENTO,
	'22050803' AS CUENTA,	
	TT.PROVEEDOR,	
	TT.ID_ACCION,
	TT.NUM_OS,	
	TT.CENTRO_COSTOS_INGRESO,
	TT.CENTRO_COSTOS_GASTOS,
	0.00::NUMERIC AS VALOR_DEB,
        SUM(TT.VALOR_DEB) AS VALOR_CREDT,
	'CXP A FINTRA TRASLADO ING MS' AS  DESCRIPCION
	
FROM(
	SELECT 
		T1.DOCUMENTO,
		T1.TIPO_DOCUMENTO,
		T1.CODIGO_CUENTA AS CUENTA,	
		T1.PROVEEDOR,	
		T1.ID_ACCION,
		T1.NUM_OS,	
		T1.CENTRO_COSTOS_INGRESO,
		T1.CENTRO_COSTOS_GASTOS,
		T1.VLR-((T1.VLR*(T1.TOTAL_DESCUENTO_FACTORING/100))) AS VALOR_DEB,
		0.00::NUMERIC AS VALOR_CREDT,
		UPPER(T1.DESCRIPCION)AS  DESCRIPCION
	      FROM (
	      SELECT CXP.PROVEEDOR,
		     CXP.TIPO_DOCUMENTO,
		     CXP.DOCUMENTO,
		     'CANCELA FACTURA CONTRATISTA POR TRASLADO A FINTRA : '||ACC.ID_ACCION AS DESCRIPCION,
		     (SUM(CXPDET.VLR)) AS VLR,
		     CXPDET.CODIGO_CUENTA,
		     ACC.ID_ACCION,
		     OFER.NUM_OS, 
		     OFER.CENTRO_COSTOS_INGRESO,
		     OFER.CENTRO_COSTOS_GASTOS,
		     ACC.POR_FACTORING_CONTRATISTA,
		     ACC.POR_FORMULA_CONTRATISTA,
		     (ACC.POR_FACTORING_CONTRATISTA+ACC.POR_FORMULA_CONTRATISTA) AS TOTAL_DESCUENTO_FACTORING,
		     CXP.FECHA_DOCUMENTO,
		     CXP.FECHA_VENCIMIENTO           
	      FROM FIN.CXP_ITEMS_DOC CXPDET
	      INNER JOIN FIN.CXP_DOC CXP ON (CXP.DOCUMENTO=CXPDET.DOCUMENTO AND CXP.TIPO_DOCUMENTO=CXPDET.TIPO_DOCUMENTO AND CXP.PROVEEDOR=CXPDET.PROVEEDOR)
	      INNER JOIN OPAV.ACCIONES ACC ON (ACC.ID_ACCION=CXPDET.REFERENCIA_1 AND ACC.REG_STATUS!='A')
	      INNER JOIN OPAV.OFERTAS AS OFER ON (ACC.ID_SOLICITUD = OFER.ID_SOLICITUD)
	      INNER JOIN PROVEEDOR AS PRV  ON (CXP.PROVEEDOR=PRV.NIT)
	      WHERE 
	      CXP.DOCUMENTO= '278'--FACTURA_NM.DOCUMENTO   ---?
	      --AND CXP.PROVEEDOR = FACTURA_NM.NIT ---?
	      AND CXP.TIPO_DOCUMENTO='FAP' 
	      AND CXP.HANDLE_CODE ='CD' 
	      AND CXP.DESCRIPCION LIKE 'Reunifica facturas internas:%'
	      AND COALESCE(PROCESADO,'N')  = 'S' 
	      GROUP BY 
	      CXP.PROVEEDOR,
	      CXP.TIPO_DOCUMENTO,
	      CXP.DOCUMENTO,
	      CXPDET.CODIGO_CUENTA,
	      ACC.ID_ACCION, 
	      ACC.POR_FACTORING_CONTRATISTA,
	      ACC.POR_FORMULA_CONTRATISTA,
	      OFER.CENTRO_COSTOS_INGRESO,
	      OFER.CENTRO_COSTOS_GASTOS,
	      OFER.NUM_OS,
	      CXP.FECHA_DOCUMENTO,
	      CXP.FECHA_VENCIMIENTO
	      
	     )T1
	UNION ALL
	SELECT 
		CXP.DOCUMENTO, 
		CXP.TIPO_DOCUMENTO,
		CXPDET.CODIGO_CUENTA AS CUENTA,	
		CXP.PROVEEDOR,	
		ACC.ID_ACCION,
		OFER.NUM_OS,	
		OFER.CENTRO_COSTOS_INGRESO,
		OFER.CENTRO_COSTOS_GASTOS,
		SUM(CXPDET.VLR) AS VALOR_DEB,
		0::NUMERIC AS VALOR_CREDT,
		UPPER(CXPDET.DESCRIPCION)AS  DESCRIPCION
		--CXPDET.*
	FROM FIN.CXP_ITEMS_DOC CXPDET
	INNER JOIN FIN.CXP_DOC CXP ON (CXPDET.DOCUMENTO =CXP.DOCUMENTO AND CXPDET.TIPO_DOCUMENTO=CXP.TIPO_DOCUMENTO )
	LEFT JOIN OPAV.ACCIONES ACC ON (ACC.ID_ACCION=CXPDET.REFERENCIA_1 AND ACC.REG_STATUS!='A')
	LEFT JOIN OPAV.OFERTAS AS OFER	ON (ACC.ID_SOLICITUD = OFER.ID_SOLICITUD)
	WHERE CXP.TIPO_DOCUMENTO= 'FAP'--FACTURA_NM.TIPO_DOCUMENTO
	AND   CXP.HANDLE_CODE = 'TF'
	AND   CXP.DOCUMENTO 	= 'T00000507' --FACTURA_NM.DOCUMENTO
	AND   CXPDET.CODIGO_CUENTA != '11050524'
	--AND   CXP.REG_STATUS		=''
	GROUP BY 
	      CXPDET.CODIGO_CUENTA, 
	      CXPDET.DESCRIPCION,
	      CXP.DOCUMENTO, 
	      CXP.TIPO_DOCUMENTO,	
	      CXP.PROVEEDOR,	
	      ACC.ID_ACCION,
	      OFER.NUM_OS,	
	      OFER.CENTRO_COSTOS_INGRESO,
	      OFER.CENTRO_COSTOS_GASTOS
)AS TT
	GROUP BY 
	TT.DOCUMENTO,
	TT.TIPO_DOCUMENTO,
	TT.PROVEEDOR,	
	TT.ID_ACCION,
	TT.NUM_OS,	
	TT.CENTRO_COSTOS_INGRESO,
	TT.CENTRO_COSTOS_GASTOS
	
	ORDER BY NUM_OS , VALOR_DEB DESC




