SELECT * FROM APOTEOSYS.MENSAJ WHERE MENSAJ_NUMEMENS__B IN (2012);

SELECT mcte.MCTEMP_CADERRVAL_B,
  mcte.*
FROM APOTEOSYS.MCTEMP mcte
WHERE mcte.MCTEMP_SECUINTE__CEP____B = '10338'
ORDER BY mcte.MC_____NUMERO____B,
         mcte.MC_____SECUINTE__DCD____B; --AND MCTEMP_CADERRVAL_B IS NOT NULL; --AND mcte.MC_____NUMERO____B=57552
ORDER BY mcte.MC_____SECUINTE__DCD____B;
SELECT * FROM APOTEOSYS.CPC___ WHERE CPC____CODIGO____B = 28151004;

SELECT * FROM APOTEOSYS.SCD___ WHERE SCD____NUMDOCSOP_B = '057';

SELECT * FROM APOTEOSYS.SCD___ WHERE SCD____CODIGO____CPC____B=23200101;

SELECT * FROM APOTEOSYS.MC____ WHERE MC_____CODIGO____CD_____B='CCSL';

SELECT * FROM APOTEOSYS.MC____ WHERE MC_____CODIGO____CD_____B='CFSL';
AND MC_____NUMERO____B=57194;
SELECT * FROM APOTEOSYS.SCD___ WHERE SCD____NUMDOCSOP_B='330';

--verificar SI CONCEPTO ESTA CREADO
SELECT *
FROM APOTEOSYS.CD____
WHERE CD_____CODIGO____B        ='CPFI';
      CD_____CODIGO____TD_____B = 'CXPN';
      CD_____CODIGO____B        ='CPFI';

SELECT *
FROM APOTEOSYS.MC____
WHERE MC_____CODIGO____CONTAB_B = 'SELE'
 AND MC_____CODIGO____TD_____B = 'CXCN'
  AND MC_____CODIGO____CD_____B = 'NMSL'
  AND MC_____NUMERO____PERIOD_B = '1';
  
SELECT * FROM APOTEOSYS.DS____ WHERE DS_____CODIGO____B='FAPR';

SELECT *
FROM APOTEOSYS.MC____
WHERE MC_____NUMDOCSOP_B IN('FR015092-13012017','BAQ9426','039','000136','4131');

SELECT                    *
FROM APOTEOSYS.MC____
WHERE MC_____CODIGO____CD_____B='CFSL'
AND MC_____NUMDOCSOP_B         = 'FV-422';

SELECT *
FROM APOTEOSYS.MC____
WHERE MC_____CODIGO____CD_____B='CPFI'
AND MC_____NUMDOCSOP_B = ''
AND MC_____NUMERO____PERIOD_B  = '4';

