SELECT 
	CPD.CUENTA 				AS CODIGO_CUENTA, 
	CPD.DETALLE || ' '||CPD.REFERENCIA_1 	AS DESCRIPCION, 
	SUM(CPD.VALOR_DEBITO) 			AS DEBITO,
	SUM(CPD.VALOR_CREDITO)			AS CREDITO,
	'A1111F32201' 				AS CENTRO_COSTO,
	CPD.TIPODOC 				AS DOCUMENTO_SOPORTE,
	CPD.NUMDOC				AS DOC_SOPORTE,
	CPD.DOCUMENTO_REL		AS REF	
	
 FROM 		CON.COMPROBANTE 	AS CP
 INNER JOIN 	CON.COMPRODET  		AS CPD 		ON (CP.NUMDOC = CPD.NUMDOC)
 WHERE 
	 CPD.TIPODOC		= 'CDIAR' 
	AND CPD.CUENTA 		= '16252115'
	AND CP.REG_STATUS 	= ''
	AND CPD.REG_STATUS 	= ''
	--AND SUBSTRING(CPD.DETALLE,1,2) = 'SV'
	AND CPD.NUMDOC = (SELECT  CPD.NUMDOC 
				FROM CON.COMPRODET CPD 
				WHERE CPD.NUMDOC LIKE 'DM%' 
				      AND CPD.CUENTA IN ('16252115','13050708') 
				      AND CPD.DOCUMENTO_REL = 'PM12743_10' 
				GROUP BY 1 )

GROUP BY 
	CPD.CUENTA,
	--CPD.DETALLE,
	CPD.TIPODOC, 
	CPD.NUMDOC,
	CPD.DOCUMENTO_REL,
	CPD.REFERENCIA_1 
union all
SELECT 
	CPD.CUENTA 		AS CODIGO_CUENTA, 
	--CPD.DETALLE || ' '||CPD.REFERENCIA_1 	AS DESCRIPCION, 
	SUM(CPD.VALOR_DEBITO) 	AS DEBITO,
	SUM(CPD.VALOR_CREDITO)	AS CREDITO,
	'A1111F32201' 		AS CENTRO_COSTO,
	CPD.TIPODOC 		AS DOCUMENTO_SOPORTE,
	CPD.NUMDOC		AS DOC_SOPORTE,
	CPD.DOCUMENTO_REL	AS REF	
	
 FROM 		CON.COMPROBANTE 	AS CP
 INNER JOIN 	CON.COMPRODET  		AS CPD 	ON (CP.NUMDOC = CPD.NUMDOC)	
 WHERE 	
	 CPD.TIPODOC		= 'CDIAR' 
	AND CPD.CUENTA 		= 13050708
	AND CP.REG_STATUS 	= ''
	AND CPD.REG_STATUS 	= ''
	--AND SUBSTRING(CPD.DETALLE,1,2) = 'SV'
	AND CPD.NUMDOC = (SELECT  CPD.NUMDOC 
				FROM CON.COMPRODET CPD 
				WHERE CPD.NUMDOC LIKE 'DM%' 
				      AND CPD.CUENTA IN ('16252115','13050708') 
				      AND CPD.DOCUMENTO_REL = 'PM12743_10' 
				GROUP BY 1 )		

GROUP BY 
	CPD.CUENTA,
	--CPD.DETALLE,
	CPD.TIPODOC, 
	CPD.NUMDOC,
	CPD.DOCUMENTO_REL,
	CPD.REFERENCIA_1